// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAPIConnectivity() {
  return window['go']['main']['App']['CheckAPIConnectivity']();
}

export function DeleteBill(arg1) {
  return window['go']['main']['App']['DeleteBill'](arg1);
}

export function DeleteToken(arg1) {
  return window['go']['main']['App']['DeleteToken'](arg1);
}

export function GetAPIService() {
  return window['go']['main']['App']['GetAPIService']();
}

export function GetAllConfigs() {
  return window['go']['main']['App']['GetAllConfigs']();
}

export function GetAllTokens() {
  return window['go']['main']['App']['GetAllTokens']();
}

export function GetBillByID(arg1) {
  return window['go']['main']['App']['GetBillByID'](arg1);
}

export function GetBills(arg1) {
  return window['go']['main']['App']['GetBills'](arg1);
}

export function GetBillsByDateRange(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetBillsByDateRange'](arg1, arg2, arg3, arg4);
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetDatabase() {
  return window['go']['main']['App']['GetDatabase']();
}

export function GetDatabaseInfo() {
  return window['go']['main']['App']['GetDatabaseInfo']();
}

export function GetHourlyUsage(arg1) {
  return window['go']['main']['App']['GetHourlyUsage'](arg1);
}

export function GetModelDistribution(arg1, arg2) {
  return window['go']['main']['App']['GetModelDistribution'](arg1, arg2);
}

export function GetRecentUsage(arg1) {
  return window['go']['main']['App']['GetRecentUsage'](arg1);
}

export function GetStats(arg1, arg2) {
  return window['go']['main']['App']['GetStats'](arg1, arg2);
}

export function GetSyncHistory(arg1, arg2) {
  return window['go']['main']['App']['GetSyncHistory'](arg1, arg2);
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetToken() {
  return window['go']['main']['App']['GetToken']();
}

export function GetUsageTrend(arg1) {
  return window['go']['main']['App']['GetUsageTrend'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveToken(arg1, arg2) {
  return window['go']['main']['App']['SaveToken'](arg1, arg2);
}

export function SetConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2, arg3);
}

export function SyncBills(arg1, arg2) {
  return window['go']['main']['App']['SyncBills'](arg1, arg2);
}

export function SyncRecentMonths(arg1) {
  return window['go']['main']['App']['SyncRecentMonths'](arg1);
}

export function ValidateSavedToken() {
  return window['go']['main']['App']['ValidateSavedToken']();
}

export function ValidateToken(arg1) {
  return window['go']['main']['App']['ValidateToken'](arg1);
}
