// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';
import {time} from '../models';
import {main} from '../models';

export function CheckAPIConnectivity():Promise<Record<string, any>>;

export function DeleteBill(arg1:number):Promise<void>;

export function DeleteToken(arg1:number):Promise<void>;

export function GetAPIService():Promise<services.APIService>;

export function GetAllConfigs():Promise<Array<models.AutoSyncConfig>>;

export function GetAllTokens():Promise<Array<models.APIToken>>;

export function GetBillByID(arg1:number):Promise<models.ExpenseBill>;

export function GetBills(arg1:models.BillFilter):Promise<models.PaginatedResult>;

export function GetBillsByDateRange(arg1:time.Time,arg2:time.Time,arg3:number,arg4:number):Promise<models.PaginatedResult>;

export function GetConfig(arg1:string):Promise<string>;

export function GetDatabase():Promise<main.Database>;

export function GetDatabaseInfo():Promise<Record<string, any>>;

export function GetHourlyUsage(arg1:number):Promise<Array<models.HourlyUsageData>>;

export function GetModelDistribution(arg1:time.Time,arg2:time.Time):Promise<Array<models.ModelDistributionData>>;

export function GetRecentUsage(arg1:number):Promise<Array<models.ExpenseBill>>;

export function GetStats(arg1:time.Time,arg2:time.Time):Promise<models.StatsResponse>;

export function GetSyncHistory(arg1:number,arg2:number):Promise<models.PaginatedResult>;

export function GetSyncStatus():Promise<models.SyncStatus>;

export function GetToken():Promise<models.APIToken>;

export function GetUsageTrend(arg1:number):Promise<Array<models.HourlyUsageData>>;

export function Greet(arg1:string):Promise<string>;

export function SaveToken(arg1:string,arg2:string):Promise<void>;

export function SetConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SyncBills(arg1:number,arg2:number):Promise<services.SyncResult>;

export function SyncRecentMonths(arg1:number):Promise<Array<services.SyncResult>>;

export function ValidateToken(arg1:string):Promise<void>;
